### ISSUE TITLE
About the  implementation code

### ISSUE THREAD

**Issue by meiyuan666** [balanced-fl/Make_FL_More_Balanced#1]
Hello，I have read your paper, Addressing Class Imbalance in Federated Learning. It is really a wonderful idea! Will you open your source code? I'm looking forward to learning it! Thanks a lot!

**Comment by xxx-Huwang** [comment]
Hi Meiyuan,

We will open our code after the AAAI conference, which is about the mid of
Feb. Thanks for your interest!

Best,
Lixu
