### ISSUE TITLE
some questions about the code

### ISSUE THREAD

**Issue by jiachenlei** [balanced-fl/Make_FL_More_Balanced#3]
Thank you for providing your code. After reading your code, I have several questions and I really appreciate it if you could answer these questions for me.

(1) In the paper, it is said that a threshold is used to select components of W_p (set to 1.25 in experiments), but I did not find any trace of it in the codes.
(2) In the code below, I don't understand the reason for setting the ratio for class p to **10** when the denominator is zero, why it should be 10 and not some other numbers? Is there any other empirical observation to support that? 
```
FEMNIST-monitor/models/Fed.py in whole_determination()
if aux_other_sum != 0:
            res = abs(aux_sum) / abs(aux_other_sum)  
        else:  
            res = 10  
```
(3) In the code, Np, the predicted number of classes p, is computed by the code below. It is confusing that the code computes the average value of Ra_pi by summing up all the nominators and denominators respectively and divides those two summations to get the ratio Ra_p for class p. Could you please explain why?
```
FEMNIST-monitor/models/Fed.py in whole_determination()
for it in range(26):
        cc_class = it
        aux_sum = 0
        aux_other_sum = 0
        layer = 1
        for i in range(pos.shape[1]):
            for j in range(pos.shape[2]):
                if pos[cc_class, i, j] == 1:
                    temp = []
                    last = w_glob_last['resnet.fc{}.weight'.format(layer)].cpu().numpy()[i, j]
                    cc = cc_net[cc_class]['resnet.fc{}.weight'.format(layer)].cpu().numpy()[i, j]
                    for p in range(len(cc_net)):
                        temp.append(cc_net[p]['resnet.fc{}.weight'.format(layer)].cpu().numpy()[i, j] - last)
                    temp = np.array(temp)
                    temp = np.delete(temp, cc_class)
                    temp_ave = np.sum(temp) / (len(cc_net) - 1)
                    aux_sum += cc - last
                    aux_other_sum += temp_ave
        if aux_other_sum != 0:
            res = abs(aux_sum) / abs(aux_other_sum)
        else:
            res = 10
```
(4) In the following code, why the predicted number of class p should be less than 1.5 times the average number of samples for each class?
```
FEMNIST-monitor/models/Fed.py in monitoring()

if 0 < res_temp < num_samples * 1.5 / num_class:
    temp_res.append(res_temp)
```

Thank you for your attention and any help/answers will be highly appreciated.

**Comment by xxx-Huwang** [comment]
Hi,

1. The threshold T_{Ra} corresponds to line 35 in Fed.py and the condition
(> 0.8) corresponds to T_{Ra}=1.25.



2. When the denominator of a particular class is relatively small even to
be 0, its weight coefficient will be extremely large, thus we set an upper
bound (10).



3. Thank you for pointing this. In our code implementation, we found if we
compute all Ra_{p, i} at first and get the average value, the corresponding
weight coefficient is highly influenced by some outlier Ra_{p, i}.
Therefore, we compute the average value by dividing sums of nominators and
denominators. Moreover, I notice that the implementation here is not the
same as our paper, sorry for that. I will mark this difference in the
Readme. Thanks again!



4. The main work of the monitor is alerting the existence of minority
classes, for the majority, the monitor does not need to pay much attention.
In our experiments, we always set the sample quantity of majority classes
to approximately the average number of samples and decrease the sample
quantity of minority classes to increase the imbalance ratio. Thus, we just
set the 1.5 times to bound the majority classes.



Thanks for your interest! We believe this work has potential improvements,
especially for the monitor, if you have any idea to make it better, we will
appreciate that contribution.


Best,

Lixu
