### ISSUE TITLE
Question about data format

### ISSUE THREAD

**Issue by Hiramdu** [balanced-fl/Make_FL_More_Balanced#4]
Hi, I see your work is using image dataset. How can I use it on a tabular format csv dataset such as: https://www.kaggle.com/wenruliu/adult-income-dataset
Thanks!

**Comment by conditionWang** [comment]
You can just write a dataset loading program to feed the data to the neural network, i.e., you need to conduct some adaptation implementation to apply our method to non-image datasets.
